"""Base configuration with stable defaults.

These settings should not change often and are safe for all environments.
"""

from pathlib import Path

# Project root directory
BASE_DIR = Path(__file__).parent.parent.absolute()

# Core settings (stable defaults)
DEFAULT_SECRET_KEY = "dev-secret-key-change-in-production"
DEFAULT_JWT_SECRET_KEY = "dev-jwt-secret-key-change-in-production-32"

# Default directories
DEFAULT_UPLOAD_FOLDER = BASE_DIR / "app" / "static" / "uploads"
DEFAULT_LOCAL_ADMIN_UPLOAD_FOLDER = BASE_DIR / "app" / "static" / "uploads_admin"
DEFAULT_BACKUP_DIR = BASE_DIR / "backups"
DEFAULT_CACHE_DIR = BASE_DIR / "data" / "cache"
DEFAULT_REPORTS_DIR = BASE_DIR / "reports"
DEFAULT_CLASSIFIER_CACHE_PATH = BASE_DIR / "data" / "classifier_cache.json"

# Default values for common settings
DEFAULT_MAX_CONTENT_LENGTH = 100 * 1024 * 1024  # 100MB
DEFAULT_AUTO_BACKUP_KEEP = 30
DEFAULT_AUTO_CREATE_DB = False

# AI defaults
DEFAULT_GEMINI_MODEL_NAME = "gemini-2.0-flash-lite"
DEFAULT_GEMINI_MAX_OUTPUT_TOKENS = 2048

# Experiment defaults
DEFAULT_RETRIEVAL_MODE = "bm25"
DEFAULT_RRF_K = 60
DEFAULT_SEARCH_BACKEND = "auto"
DEFAULT_SEARCH_PG_QUERY_MODE = "websearch"
DEFAULT_SEARCH_PG_TRGM_ENABLED = False
DEFAULT_SEARCH_PG_TRGM_MIN_SIMILARITY = 0.2
DEFAULT_SEARCH_PG_TRGM_TOP_N = 40
DEFAULT_SEARCH_PG_TRGM_ALPHA = 0.3
DEFAULT_SEARCH_PG_TRGM_BLEND_MODE = "conditional"  # conditional | always | off
DEFAULT_SEARCH_PG_TRGM_MIN_BM25_RESULTS = 10
# Lecture aggregation
DEFAULT_LECTURE_AGG_MODE = "topm_mean"   # sum | topm_mean
DEFAULT_LECTURE_TOPM = 3
DEFAULT_LECTURE_CHUNK_CAP = 0      # 0 = disabled

DEFAULT_CLASSIFIER_ALLOW_ID_FROM_TEXT = False
DEFAULT_CLASSIFIER_REQUIRE_VERBATIM_QUOTE = True
DEFAULT_CLASSIFIER_REQUIRE_PAGE_SPAN = True
DEFAULT_CLASSIFIER_REJUDGE_ENABLED = True
DEFAULT_CLASSIFIER_REJUDGE_MIN_CANDIDATES = 3
DEFAULT_CLASSIFIER_REJUDGE_TOP_K = 8
DEFAULT_CLASSIFIER_REJUDGE_EVIDENCE_PER_LECTURE = 6
DEFAULT_CLASSIFIER_REJUDGE_MIN_CONFIDENCE_STRICT = 0.80
DEFAULT_CLASSIFIER_REJUDGE_ALLOW_WEAK_MATCH = True
DEFAULT_CLASSIFIER_REJUDGE_MIN_CONFIDENCE_WEAK = 0.65

# HYDE defaults
DEFAULT_HYDE_ENABLED = False
DEFAULT_HYDE_AUTO_GENERATE = False
DEFAULT_HYDE_PROMPT_VERSION = "hyde_v1"
DEFAULT_HYDE_STRATEGY = "blend"
DEFAULT_HYDE_BM25_VARIANT = "mixed_light"
DEFAULT_HYDE_NEGATIVE_MODE = "stopwords"
DEFAULT_HYDE_MARGIN_EPS = 0.0
DEFAULT_HYDE_MAX_KEYWORDS = 7
DEFAULT_HYDE_MAX_NEGATIVE = 6

# PDF parser
DEFAULT_PDF_PARSER_MODE = "legacy"

# Auto-Confirm V2
DEFAULT_AUTO_CONFIRM_V2_ENABLED = True
DEFAULT_AUTO_CONFIRM_V2_DELTA = 0.05
DEFAULT_AUTO_CONFIRM_V2_MAX_BM25_RANK = 5
DEFAULT_AUTO_CONFIRM_V2_DELTA_UNCERTAIN = 0.03
DEFAULT_AUTO_CONFIRM_V2_MIN_CHUNK_LEN = 200

# Context Expansion
DEFAULT_PARENT_ENABLED = False
DEFAULT_PARENT_WINDOW_PAGES = 1
DEFAULT_PARENT_MAX_CHARS = 3500
DEFAULT_PARENT_TOPK = 5
DEFAULT_SEMANTIC_EXPANSION_ENABLED = True
DEFAULT_SEMANTIC_EXPANSION_TOP_N = 6
DEFAULT_SEMANTIC_EXPANSION_MAX_EXTRA = 2
DEFAULT_SEMANTIC_EXPANSION_QUERY_MAX_CHARS = 1200

# CORS
DEFAULT_CORS_ALLOWED_ORIGINS = "http://localhost:4000"
DEFAULT_CORS_ALLOWED_ORIGINS_PROD = "https://your-domain.com"

__all__ = [
    "BASE_DIR",
    "DEFAULT_SECRET_KEY",
    "DEFAULT_JWT_SECRET_KEY",
    "DEFAULT_UPLOAD_FOLDER",
    "DEFAULT_LOCAL_ADMIN_UPLOAD_FOLDER",
    "DEFAULT_BACKUP_DIR",
    "DEFAULT_CACHE_DIR",
    "DEFAULT_REPORTS_DIR",
    "DEFAULT_CLASSIFIER_CACHE_PATH",
    "DEFAULT_MAX_CONTENT_LENGTH",
    "DEFAULT_AUTO_BACKUP_KEEP",
    "DEFAULT_AUTO_CREATE_DB",
    "DEFAULT_GEMINI_MODEL_NAME",
    "DEFAULT_GEMINI_MAX_OUTPUT_TOKENS",
    "DEFAULT_RETRIEVAL_MODE",
    "DEFAULT_RRF_K",
    "DEFAULT_SEARCH_BACKEND",
    "DEFAULT_SEARCH_PG_QUERY_MODE",
    "DEFAULT_SEARCH_PG_TRGM_ENABLED",
    "DEFAULT_SEARCH_PG_TRGM_MIN_SIMILARITY",
    "DEFAULT_SEARCH_PG_TRGM_TOP_N",
    "DEFAULT_SEARCH_PG_TRGM_ALPHA",
    "DEFAULT_SEARCH_PG_TRGM_BLEND_MODE",
    "DEFAULT_SEARCH_PG_TRGM_MIN_BM25_RESULTS",
    "DEFAULT_LECTURE_AGG_MODE",
    "DEFAULT_LECTURE_TOPM",
    "DEFAULT_LECTURE_CHUNK_CAP",
    "DEFAULT_CLASSIFIER_ALLOW_ID_FROM_TEXT",
    "DEFAULT_CLASSIFIER_REQUIRE_VERBATIM_QUOTE",
    "DEFAULT_CLASSIFIER_REQUIRE_PAGE_SPAN",
    "DEFAULT_CLASSIFIER_REJUDGE_ENABLED",
    "DEFAULT_CLASSIFIER_REJUDGE_MIN_CANDIDATES",
    "DEFAULT_CLASSIFIER_REJUDGE_TOP_K",
    "DEFAULT_CLASSIFIER_REJUDGE_EVIDENCE_PER_LECTURE",
    "DEFAULT_CLASSIFIER_REJUDGE_MIN_CONFIDENCE_STRICT",
    "DEFAULT_CLASSIFIER_REJUDGE_ALLOW_WEAK_MATCH",
    "DEFAULT_CLASSIFIER_REJUDGE_MIN_CONFIDENCE_WEAK",
    "DEFAULT_HYDE_ENABLED",
    "DEFAULT_HYDE_AUTO_GENERATE",
    "DEFAULT_HYDE_PROMPT_VERSION",
    "DEFAULT_HYDE_STRATEGY",
    "DEFAULT_HYDE_BM25_VARIANT",
    "DEFAULT_HYDE_NEGATIVE_MODE",
    "DEFAULT_HYDE_MARGIN_EPS",
    "DEFAULT_HYDE_MAX_KEYWORDS",
    "DEFAULT_HYDE_MAX_NEGATIVE",
    "DEFAULT_PDF_PARSER_MODE",
    "DEFAULT_AUTO_CONFIRM_V2_ENABLED",
    "DEFAULT_AUTO_CONFIRM_V2_DELTA",
    "DEFAULT_AUTO_CONFIRM_V2_MAX_BM25_RANK",
    "DEFAULT_AUTO_CONFIRM_V2_DELTA_UNCERTAIN",
    "DEFAULT_AUTO_CONFIRM_V2_MIN_CHUNK_LEN",
    "DEFAULT_PARENT_ENABLED",
    "DEFAULT_PARENT_WINDOW_PAGES",
    "DEFAULT_PARENT_MAX_CHARS",
    "DEFAULT_PARENT_TOPK",
    "DEFAULT_SEMANTIC_EXPANSION_ENABLED",
    "DEFAULT_SEMANTIC_EXPANSION_TOP_N",
    "DEFAULT_SEMANTIC_EXPANSION_MAX_EXTRA",
    "DEFAULT_SEMANTIC_EXPANSION_QUERY_MAX_CHARS",
    "DEFAULT_CORS_ALLOWED_ORIGINS",
    "DEFAULT_CORS_ALLOWED_ORIGINS_PROD",
]
